import type { Prato, Extra, Pedido, Mensalista, Venda, ReceitaSemanal } from './types'

export const extras: Extra[] = [
  { id: 'e1', nome: 'Ovo frito', preco: 3.5 },
  { id: 'e2', nome: 'Porção de arroz', preco: 4.0 },
  { id: 'e3', nome: 'Farofa', preco: 5.0 },
  { id: 'e4', nome: 'Salada extra', preco: 3.0 },
  { id: 'e5', nome: 'Feijão extra', preco: 3.5 },
  { id: 'e6', nome: 'Molho especial', preco: 2.5 },
]

export const pratosIniciais: Prato[] = [
  // Proteínas
  {
    id: 'p1',
    nome: 'Frango Acebolado',
    descricao: 'Frango grelhado com cebola caramelizada e temperos especiais da casa',
    preco: 12.0,
    categoria: 'proteina',
    imagem: 'https://images.unsplash.com/photo-1532550907402-a621b094548d?w=400&q=80',
    acompanhamentos: ['Arroz', 'Feijão', 'Salada'],
    disponivel: true,
  },
  {
    id: 'p2',
    nome: 'Bife Acebolado',
    descricao: 'Bife bovino grelhado com cebola e alho, suculento e temperado',
    preco: 15.0,
    categoria: 'proteina',
    imagem: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80',
    acompanhamentos: ['Arroz', 'Feijão', 'Farofa'],
    disponivel: true,
  },
  {
    id: 'p3',
    nome: 'Tilápia Grelhada',
    descricao: 'Filé de tilápia grelhado com limão e ervas frescas',
    preco: 16.5,
    categoria: 'proteina',
    imagem: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&q=80',
    acompanhamentos: ['Arroz', 'Purê', 'Salada'],
    disponivel: true,
  },
  {
    id: 'p4',
    nome: 'Frango ao Molho Pardo',
    descricao: 'Frango caipira cozido em molho escuro com temperos tradicionais',
    preco: 14.0,
    categoria: 'proteina',
    imagem: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&q=80',
    acompanhamentos: ['Arroz', 'Angu', 'Couve'],
    disponivel: true,
  },
  {
    id: 'p5',
    nome: 'Costelinha Suína',
    descricao: 'Costelinha de porco assada com molho barbecue artesanal',
    preco: 18.0,
    categoria: 'proteina',
    imagem: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400&q=80',
    acompanhamentos: ['Arroz', 'Farofa', 'Vinagrete'],
    disponivel: false,
  },
  {
    id: 'p6',
    nome: 'Ovo de Vez',
    descricao: 'Ovo mexido com legumes salteados na manteiga',
    preco: 9.0,
    categoria: 'proteina',
    imagem: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=400&q=80',
    acompanhamentos: ['Arroz', 'Feijão'],
    disponivel: true,
  },
  // Carboidratos
  {
    id: 'c1',
    nome: 'Macarrão ao Sugo',
    descricao: 'Macarrão artesanal com molho de tomate fresco e manjericão',
    preco: 10.0,
    categoria: 'carboidrato',
    imagem: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80',
    acompanhamentos: ['Salada', 'Pão de alho'],
    disponivel: true,
  },
  {
    id: 'c2',
    nome: 'Macarrão à Bolonhesa',
    descricao: 'Espaguete com ragu de carne moída e tomate',
    preco: 13.0,
    categoria: 'carboidrato',
    imagem: 'https://images.unsplash.com/photo-1585238342026-7c6ee049600b?w=400&q=80',
    acompanhamentos: ['Salada', 'Pão'],
    disponivel: true,
  },
  {
    id: 'c3',
    nome: 'Batata Assada Recheada',
    descricao: 'Batata rústica assada recheada com creme de manteiga e ervas',
    preco: 11.0,
    categoria: 'carboidrato',
    imagem: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80',
    acompanhamentos: ['Salada'],
    disponivel: true,
  },
  // Grãos
  {
    id: 'g1',
    nome: 'Feijão Tropeiro',
    descricao: 'Feijão com bacon, linguiça, farinha e couve na chapa',
    preco: 13.5,
    categoria: 'graos',
    imagem: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&q=80',
    acompanhamentos: ['Arroz', 'Ovo frito'],
    disponivel: true,
  },
  {
    id: 'g2',
    nome: 'Lentilha ao Curry',
    descricao: 'Lentilhas cozidas com curry suave, cúrcuma e leite de coco',
    preco: 11.0,
    categoria: 'graos',
    imagem: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    acompanhamentos: ['Arroz integral'],
    disponivel: true,
  },
  {
    id: 'g3',
    nome: 'Feijoada Completa',
    descricao: 'Feijoada tradicional com carnes defumadas, couve e laranja',
    preco: 22.0,
    categoria: 'graos',
    imagem: 'https://images.unsplash.com/photo-1598568977558-6c1e0a8f6d5e?w=400&q=80',
    acompanhamentos: ['Arroz', 'Farofa', 'Couve', 'Laranja'],
    disponivel: false,
  },
  // Saladas
  {
    id: 's1',
    nome: 'Salada Caesar',
    descricao: 'Alface romana, croutons, parmesão e molho caesar clássico',
    preco: 9.0,
    categoria: 'salada',
    imagem: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80',
    acompanhamentos: [],
    disponivel: true,
  },
  {
    id: 's2',
    nome: 'Salada Tropical',
    descricao: 'Mix verde com manga, abacate, tomate e vinagrete de maracujá',
    preco: 10.5,
    categoria: 'salada',
    imagem: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
    acompanhamentos: [],
    disponivel: true,
  },
  {
    id: 's3',
    nome: 'Salada de Grão de Bico',
    descricao: 'Grão de bico com tomate cereja, cebola roxa e salsinha',
    preco: 8.5,
    categoria: 'salada',
    imagem: 'https://images.unsplash.com/photo-1529059997568-3d847b1154f0?w=400&q=80',
    acompanhamentos: [],
    disponivel: true,
  },
  // Bebidas
  {
    id: 'b1',
    nome: 'Suco de Laranja Natural',
    descricao: 'Suco de laranja espremido na hora, 400ml',
    preco: 6.0,
    categoria: 'bebida',
    imagem: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&q=80',
    acompanhamentos: [],
    disponivel: true,
  },
  {
    id: 'b2',
    nome: 'Suco de Açaí com Banana',
    descricao: 'Suco cremoso de açaí com banana e mel, 400ml',
    preco: 9.0,
    categoria: 'bebida',
    imagem: 'https://images.unsplash.com/photo-1638336726900-fce869048d0e?w=400&q=80',
    acompanhamentos: [],
    disponivel: true,
  },
  {
    id: 'b3',
    nome: 'Limonada Suíça',
    descricao: 'Limonada cremosa com leite condensado e limão tahiti, 400ml',
    preco: 8.0,
    categoria: 'bebida',
    imagem: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&q=80',
    acompanhamentos: [],
    disponivel: true,
  },
  {
    id: 'b4',
    nome: 'Água Mineral',
    descricao: 'Água mineral sem gás 500ml',
    preco: 3.0,
    categoria: 'bebida',
    imagem: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400&q=80',
    acompanhamentos: [],
    disponivel: true,
  },
  // Sobremesas
  {
    id: 'sb1',
    nome: 'Pudim de Leite',
    descricao: 'Pudim cremoso de leite condensado com calda de caramelo',
    preco: 7.0,
    categoria: 'sobremesa',
    imagem: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80',
    acompanhamentos: [],
    disponivel: true,
  },
  {
    id: 'sb2',
    nome: 'Mousse de Maracujá',
    descricao: 'Mousse leve de maracujá com calda da fruta',
    preco: 8.0,
    categoria: 'sobremesa',
    imagem: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80',
    acompanhamentos: [],
    disponivel: true,
  },
  {
    id: 'sb3',
    nome: 'Bolo de Cenoura',
    descricao: 'Fatia de bolo de cenoura com cobertura de chocolate',
    preco: 6.5,
    categoria: 'sobremesa',
    imagem: 'https://images.unsplash.com/photo-1598461558369-70d30d3e8b0b?w=400&q=80',
    acompanhamentos: [],
    disponivel: true,
  },
  {
    id: 'sb4',
    nome: 'Açaí na Tigela',
    descricao: 'Açaí cremoso com granola, banana e mel',
    preco: 12.0,
    categoria: 'sobremesa',
    imagem: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&q=80',
    acompanhamentos: [],
    disponivel: true,
  },
]

export const pedidosIniciais: Pedido[] = [
  {
    id: 'ord1',
    numero: 1001,
    items: [
      { prato: pratosIniciais[0], quantidade: 2, extras: [extras[0]], nota: 'Sem cebola' },
      { prato: pratosIniciais[16], quantidade: 2, extras: [] },
    ],
    status: 'novo',
    tipo: 'avulso',
    total: 36.0,
    criadoEm: new Date('2024-07-07T11:30:00'),
    modoRecebimento: 'entrega',
    enderecoEntrega: 'Rua das Flores, 123 - Centro',
    formaPagamento: 'pix',
  },
  {
    id: 'ord2',
    numero: 1002,
    items: [
      { prato: pratosIniciais[1], quantidade: 1, extras: [extras[2]], nota: '' },
      { prato: pratosIniciais[9], quantidade: 1, extras: [] },
    ],
    status: 'preparo',
    tipo: 'mensalista',
    clienteNome: 'Maria Silva',
    total: 33.5,
    criadoEm: new Date('2024-07-07T11:15:00'),
    modoRecebimento: 'retirada',
    formaPagamento: 'mensalista',
  },
  {
    id: 'ord3',
    numero: 1003,
    items: [
      { prato: pratosIniciais[2], quantidade: 1, extras: [] },
      { prato: pratosIniciais[12], quantidade: 1, extras: [] },
    ],
    status: 'pronto',
    tipo: 'avulso',
    total: 25.5,
    criadoEm: new Date('2024-07-07T11:00:00'),
    modoRecebimento: 'no_local',
    formaPagamento: 'credito',
  },
  {
    id: 'ord4',
    numero: 1004,
    items: [
      { prato: pratosIniciais[3], quantidade: 1, extras: [extras[3]] },
    ],
    status: 'entregue',
    tipo: 'mensalista',
    clienteNome: 'João Santos',
    total: 17.0,
    criadoEm: new Date('2024-07-07T10:45:00'),
    modoRecebimento: 'entrega',
    enderecoEntrega: 'Av. Brasil, 456 - Bairro Novo',
    formaPagamento: 'mensalista',
  },
  {
    id: 'ord5',
    numero: 1005,
    items: [
      { prato: pratosIniciais[6], quantidade: 1, extras: [] },
      { prato: pratosIniciais[20], quantidade: 1, extras: [] },
    ],
    status: 'novo',
    tipo: 'avulso',
    total: 19.0,
    criadoEm: new Date('2024-07-07T11:45:00'),
    modoRecebimento: 'retirada',
    formaPagamento: 'debito',
  },
]

export const mensalistasIniciais: Mensalista[] = [
  {
    id: 'm1',
    nome: 'Maria Silva',
    cpf: '123.456.789-00',
    email: 'maria.silva@email.com',
    telefone: '(31) 99999-1234',
    taxaMensal: 19.9,
    status: 'ativo',
    registroStatus: 'confirmado',
    criadoEm: new Date('2024-01-10'),
    totalGasto: 87.5,
  },
  {
    id: 'm2',
    nome: 'João Santos',
    cpf: '987.654.321-00',
    email: 'joao.santos@email.com',
    telefone: '(31) 99888-5678',
    taxaMensal: 19.9,
    status: 'ativo',
    registroStatus: 'confirmado',
    criadoEm: new Date('2024-02-15'),
    totalGasto: 63.0,
  },
  {
    id: 'm3',
    nome: 'Ana Costa',
    cpf: '456.789.123-00',
    email: 'ana.costa@email.com',
    telefone: '(31) 97777-9012',
    taxaMensal: 19.9,
    status: 'ativo',
    registroStatus: 'pendente',
    criadoEm: new Date('2024-03-20'),
    totalGasto: 41.0,
  },
  {
    id: 'm4',
    nome: 'Pedro Lima',
    cpf: '321.654.987-00',
    email: 'pedro.lima@email.com',
    telefone: '(31) 96666-3456',
    taxaMensal: 19.9,
    status: 'inativo',
    registroStatus: 'confirmado',
    criadoEm: new Date('2024-01-05'),
    totalGasto: 29.0,
  },
  {
    id: 'm5',
    nome: 'Carla Ferreira',
    cpf: '654.321.098-00',
    email: 'carla.ferreira@email.com',
    telefone: '(31) 95555-7890',
    taxaMensal: 19.9,
    status: 'ativo',
    registroStatus: 'confirmado',
    criadoEm: new Date('2024-04-01'),
    totalGasto: 102.5,
  },
]

export const vendasIniciais: Venda[] = [
  { id: 'v1', data: new Date('2024-07-01'), pratoNome: 'Frango Acebolado', quantidade: 8, total: 96.0, tipo: 'avulso' },
  { id: 'v2', data: new Date('2024-07-01'), pratoNome: 'Bife Acebolado', quantidade: 5, total: 75.0, tipo: 'mensalista' },
  { id: 'v3', data: new Date('2024-07-02'), pratoNome: 'Tilápia Grelhada', quantidade: 6, total: 99.0, tipo: 'avulso' },
  { id: 'v4', data: new Date('2024-07-02'), pratoNome: 'Frango Acebolado', quantidade: 10, total: 120.0, tipo: 'avulso' },
  { id: 'v5', data: new Date('2024-07-03'), pratoNome: 'Feijoada Completa', quantidade: 12, total: 264.0, tipo: 'mensalista' },
  { id: 'v6', data: new Date('2024-07-03'), pratoNome: 'Macarrão ao Sugo', quantidade: 7, total: 70.0, tipo: 'avulso' },
  { id: 'v7', data: new Date('2024-07-04'), pratoNome: 'Feijão Tropeiro', quantidade: 9, total: 121.5, tipo: 'avulso' },
  { id: 'v8', data: new Date('2024-07-04'), pratoNome: 'Bife Acebolado', quantidade: 4, total: 60.0, tipo: 'mensalista' },
  { id: 'v9', data: new Date('2024-07-05'), pratoNome: 'Frango Acebolado', quantidade: 11, total: 132.0, tipo: 'avulso' },
  { id: 'v10', data: new Date('2024-07-06'), pratoNome: 'Costelinha Suína', quantidade: 6, total: 108.0, tipo: 'avulso' },
  { id: 'v11', data: new Date('2024-07-06'), pratoNome: 'Tilápia Grelhada', quantidade: 8, total: 132.0, tipo: 'mensalista' },
  { id: 'v12', data: new Date('2024-07-07'), pratoNome: 'Frango Acebolado', quantidade: 7, total: 84.0, tipo: 'avulso' },
]

export const receitaSemanal: ReceitaSemanal[] = [
  { dia: 'Seg', avulso: 171.0, mensalista: 75.0 },
  { dia: 'Ter', avulso: 219.0, mensalista: 0 },
  { dia: 'Qua', avulso: 70.0, mensalista: 264.0 },
  { dia: 'Qui', avulso: 121.5, mensalista: 60.0 },
  { dia: 'Sex', avulso: 132.0, mensalista: 0 },
  { dia: 'Sáb', avulso: 108.0, mensalista: 132.0 },
  { dia: 'Dom', avulso: 84.0, mensalista: 0 },
]
